
CREATE TABLE DWH.`DIM_VEHICULO` (
  `SK_VEHICULO` bigint(11) NOT NULL AUTO_INCREMENT,
  `COD_VEHICULO` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `COD_EMPRESA` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `COD_LINEA_NEGOCIO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CHASIS` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `PLACA` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `MARCA` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `ANIO_VEHICULO` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `SFX` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `MODELO` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `FECHA_CARGA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha en la que se realizo la carga' ,
  KEY `SK_VEHICULO` (`SK_VEHICULO`,`COD_VEHICULO`,`COD_EMPRESA`,`COD_LINEA_NEGOCIO`) /*!90619 USING CLUSTERED COLUMNSTORE */,
  /*!90618 SHARD */ KEY `SK_VEHICULO_2` (`SK_VEHICULO`)
)/*!90621 AUTOSTATS_ENABLED=TRUE */







