
CREATE OR REPLACE PROCEDURE `CRG_INT_VENTAS_NUEVOS`(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_EMPRESA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_FECHA_INICIO date NULL, VAR_FECHA_FIN date NULL, VAR_LINEA_NEGOCIO_1 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL) RETURNS void AS
/***********************************************************************************************************************
  * Descripcion: Cargar Datos DIM_AGENCIA
  * Version: 1.0.0
  * Fecha Creacion: 24/07/2019
  * Autor: Viviana Herrera
  * Comentario : Para Ejecutar = CALL CRG_INT_VENTAS_NUEVOS('SQUEMA', 'EMPRESA', 'FECHA_INICIO', 'FECHA_FIN','LINEA_NEGOCIO_1', 'LINEA_NEGOCIO_2')
  -------------------------------------------------------------------------
  * Fecha Modificacion:
  * Modificado:
*************************************************************************************************************************/
DECLARE
	VAR_SQL VARCHAR(4000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN
START TRANSACTION;

	
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('INTERMEDIA',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_INT_VENTAS_NUEVOS'),VAR_DT_INICIO);
	COMMIT;

	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.INT_VENTAS_NUEVOS');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;
	
	VAR_SQL=CONCAT('CREATE TABLE DSA.INT_VENTAS_NUEVOS (KEY (COD_FACTURA) USING CLUSTERED COLUMNSTORE)
	AS
	SELECT 
	FECHA AS FECHA_FACTURA,COD_EMPRESA, SERIE_FISICO as COD_LINEA_NEGOCIO,COD_AGENCIA,TIPO_DOC AS COD_TIPO_DOCUMENTO,NO_VENDEDOR AS COD_VENDEDOR, NO_FACTU AS COD_FACTURA,
	NO_FISICO AS COD_NO_FISICO, NO_PEDIDO AS COD_COTIZACION,COD_TIPO_FORMA_PAGO, CHASIS AS COD_CHASIS, COD_VEHICULO_INTERES, VERSION_VEH AS COD_VERSION_VEHICULO,
	NO_CLIENTE AS COD_CLIENTE, CLASE_VEHICULOS AS COD_CLASE_CLIENTE	, LINEA AS COD_ENTIDAD,
	SUM(COSTO_VEHICULO)COSTO_VEHICULO, SUM(PRECIO)PRECIO, SUM(DESCUENTO)DESCUENTO, SUM(SUBTOTAL_MASIVO)SUBTOTAL_MASIVO  ,
	SUM(UTILIDAD)UTILIDAD, SUM(NETO)AS VALOR_NETO, SUM(SALDO_FINANCIAR) AS SALDO_FINANCIAR, SUM(CUOTA_DE_ALCANCE) AS COUTA_DE_ALCANCE
	FROM
	(select DISTINCT  A.FECHA, A.NO_FACTU, A.NO_FISICO, A.TIPO_DOC, A.NO_VENDEDOR, A.NBR_CLIENTE, A.CEDULA, B.CHASIS, E.SVMADESCRI AS MODELO, 
	NVL(A.LINEA, G.ENTIDAD) LINEA, A.NO_PEDIDO, NVL(I.VERSION_VEH, C.VERSION_ACC) AS VERSION_VEH,  I.SALDO_FINANCIAR, I.CUOTA_DE_ALCANCE, 
	A.TOTAL AS SUBTOTAL_MASIVO, B.PRECIO, B.DESCUENTO, B.PRECIO - C.SVINCOSTDO- B.DESCUENTO AS UTILIDAD, A.SUB_TOTAL NETO, C.SVINCOSTDO COSTO_VEHICULO,
	DECODE(A.CENTRO_ORIGEN, NULL, A.CENTROD, A.CENTRO_ORIGEN) AS COD_AGENCIA, A.NO_CIA COD_EMPRESA, D.NO_CLIENTE, D.CLASE_VEHICULOS, A.SERIE_FISICO,
	DECODE(A.SALDO_FACTURA,0,"CON","CRE") COD_TIPO_FORMA_PAGO, K.id AS COD_VEHICULO_INTERES
	from DSA.S3S_FAC_VENTAS_CAB A
	INNER JOIN DSA.S3S_FAC_VENTAS_VEHICULOS B ON A.NO_CIA = B.NO_CIA AND A.RUTA = B.RUTA AND A.TIPO_DOC = B.TIPO_DOC AND A.NO_FACTU = B.NO_FACTU
	INNER JOIN DSA.S3S_SVFINVEN C ON B.NO_CIA = C.NO_CIA AND B.CHASIS = C.SVINCODI
	INNER JOIN DSA.S3S_ARCCMC D ON A.NO_CIA = D.NO_CIA AND A.GRUPO = D.GRUPO AND A.NO_CLIENTE = D.NO_CLIENTE
	INNER JOIN DSA.S3S_SVFMASTER E ON C.NO_CIA = E.NO_CIA AND C.SVMAMASTER = E.SVMAMASTER AND C.SFX = E.SFX
	INNER JOIN DSA.S3S_AGENCIAS F ON A.NO_CIA = F.NO_CIA AND A.CENTROD = F.CODIGO
	INNER JOIN DSA.S3S_ARCCTF G ON A.NO_CIA = G.NO_CIA AND A.LINEA = G.TIPO
	INNER JOIN DSA.S3S_SVFTRANSA H ON A.NO_CIA = H.NO_CIA AND A.TIPO_DOC = H.SVTITIPO AND CAST(A.NO_FISICO AS UNSIGNED) = H.SVTRNUME AND A.CEDULA = H.SVTRCLCODI AND 
	B.CHASIS = H.SVINCODI AND CAST(A.FECHA AS DATE) = CAST(H.SVTRFECHA AS DATE)
	LEFT JOIN DSA.S3S_SVFCOTI I ON  A.CENTROD = I.CENTRO AND A.NO_PEDIDO = I.NUMERO_COTIZACION AND I.SVLICODI = ',VAR_LINEA_NEGOCIO_1,' AND A.NO_CIA = I.NO_CIA
	LEFT JOIN DSA.CRM_CB_LINEANEGOCIO J ON A.NO_CIA=',VAR_EMPRESA,' AND A.SERIE_FISICO=J.s3s_id
 	LEFT JOIN DSA.CRM_PP_VEHICULOS_INTERESADO K ON K.linea_negocio = J.id  AND NVL(B.SVMAMASTER, C.SVMAMASTER ) = K.SVMAMASTER AND NVL(B.SFX,C.SFX) = K.SFX
	WHERE  A.NO_CIA = ',VAR_EMPRESA,'  AND A.SERIE_FISICO = ',VAR_LINEA_NEGOCIO_1,' AND NVL(A.IND_ANU_DEV,"X")<>"A"	
	AND CAST(A.FECHA AS DATE) BETWEEN "',VAR_FECHA_INICIO,'"   AND "',VAR_FECHA_FIN,'"
	AND NOT EXISTS (SELECT 1 FROM DSA.S3S_FAC_VENTAS_CAB NC WHERE NC.NO_CIA = A.NO_CIA AND NC.NO_FISICO = A.REFER AND NC.LINEA_NEGOCIO = A.LINEA_NEGOCIO
						AND NC.TIPO_DOC = DECODE(A.KM,"NC", "FD", "AA") AND NC.CENTROD = A.CENTROD 
						AND TO_CHAR(NC.FECHA,"MM/YYYY") = TO_CHAR(A.FECHA,"MM/YYYY") AND NC.NO_FACTU_REFE = A.NO_FACTU AND NC.LINEA_NEGOCIO <>"7")
	AND NOT EXISTS 	(SELECT 1 FROM DSA.S3S_FAC_VENTAS_CAB NC WHERE NC.NO_CIA = A.NO_CIA AND NC.LINEA_NEGOCIO = A.LINEA_NEGOCIO
						AND NC.CENTROD = A.CENTROD
						AND TO_CHAR(NC.FECHA,"MM/YYYY") = TO_CHAR(A.FECHA,"MM/YYYY")  AND NC.NO_FACTU_REFE = A.NO_FACTU AND NC.LINEA_NEGOCIO <>"7")	
	)A
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
	');
	EXECUTE IMMEDIATE VAR_SQL;

	COMMIT;
	
	VAR_SQL=CONCAT('INSERT INTO DSA.INT_VENTAS_NUEVOS
	SELECT 
	FECHA AS FECHA_FACTURA,COD_EMPRESA, LINEA_NEGOCIO as COD_LINEA_NEGOCIO,COD_AGENCIA,TIPO_DOC AS COD_TIPO_DOCUMENTO,NO_VENDEDOR AS COD_VENDEDOR, NO_FACTU AS COD_FACTURA, 
	NO_FISICO AS COD_NO_FISICO, NO_PEDIDO AS COD_COTIZACION,COD_TIPO_FORMA_PAGO,CHASIS AS COD_CHASIS,COD_VEHICULO_INTERES ,VERSION_VEH AS COD_VERSION_VEHICULO,
	NO_CLIENTE AS COD_CLIENTE, CLASE_VEHICULOS AS COD_CLASE_CLIENTE	, LINEA AS COD_ENTIDAD, 
	SUM(COSTO_VEHICULO)COSTO_VEHICULO, SUM(PRECIO)PRECIO, SUM(DESCUENTO)DESCUENTO, SUM(SUBTOTAL_MASIVO)SUBTOTAL_MASIVO ,
	SUM(UTILIDAD)UTILIDAD, SUM(NETO)AS VALOR_NETO , SUM(SALDO_FINANCIAR) AS SALDO_FINANCIAR, SUM(CUOTA_DE_ALCANCE) AS COUTA_DE_ALCANCE
	FROM
	(select DISTINCT  A.FECHA, A.NO_FACTU, A.NO_FISICO, A.TIPO_DOC, A.NO_VENDEDOR, A.NBR_CLIENTE, A.CEDULA, B.CHASIS, E.SVMADESCRI AS MODELO, 
	NVL(A.LINEA, G.ENTIDAD) LINEA,  A.NO_PEDIDO, NVL(I.VERSION_VEH, C.VERSION_ACC) AS VERSION_VEH,I.SALDO_FINANCIAR, I.CUOTA_DE_ALCANCE, 
	A.TOTAL AS SUBTOTAL_MASIVO, B.PRECIO, B.DESCUENTO, B.PRECIO - C.SVINCOSTDO- B.DESCUENTO AS UTILIDAD, A.SUB_TOTAL NETO, C.SVINCOSTDO COSTO_VEHICULO,
	DECODE(A.CENTRO_ORIGEN, NULL, A.CENTROD, A.CENTRO_ORIGEN) AS COD_AGENCIA, A.NO_CIA AS COD_EMPRESA, D.NO_CLIENTE, D.CLASE_VEHICULOS, A.LINEA_NEGOCIO,
	DECODE(A.SALDO_FACTURA,0,"CON","CRE") COD_TIPO_FORMA_PAGO , K.id AS COD_VEHICULO_INTERES
	from DSA.S3S_FAC_VENTAS_CAB A
	INNER JOIN DSA.S3S_FAC_VENTAS_VEHICULOS B ON A.NO_CIA = B.NO_CIA AND A.RUTA = B.RUTA AND A.TIPO_DOC = B.TIPO_DOC AND A.NO_FACTU = B.NO_FACTU
	INNER JOIN DSA.S3S_SVFINVEN C ON B.NO_CIA = C.NO_CIA AND B.CHASIS = C.SVINCODI
	INNER JOIN DSA.S3S_ARCCMC D ON A.NO_CIA = D.NO_CIA AND A.GRUPO = D.GRUPO AND A.NO_CLIENTE = D.NO_CLIENTE
	INNER JOIN DSA.S3S_SVFMASTER E ON C.NO_CIA = E.NO_CIA AND C.SVMAMASTER = E.SVMAMASTER AND C.SFX = E.SFX
	INNER JOIN DSA.S3S_AGENCIAS F ON A.NO_CIA = F.NO_CIA AND A.CENTROD = F.CODIGO
	INNER JOIN DSA.S3S_ARCCTF G ON A.NO_CIA = G.NO_CIA AND A.LINEA = G.TIPO
	INNER JOIN DSA.S3S_SVFTRANSA H ON A.NO_CIA = H.NO_CIA AND A.TIPO_DOC = H.SVTITIPO AND CAST(A.NO_FISICO AS UNSIGNED) = H.SVTRNUME AND A.CEDULA = H.SVTRCLCODI AND 
	B.CHASIS = H.SVINCODI AND CAST(A.FECHA AS DATE) = CAST(H.SVTRFECHA AS DATE)
	LEFT JOIN DSA.S3S_SVFCOTI I ON  A.CENTROD = I.CENTRO AND A.NO_PEDIDO = I.NUMERO_COTIZACION AND I.SVLICODI = ',VAR_LINEA_NEGOCIO_1,' AND A.NO_CIA = I.NO_CIA
	LEFT JOIN DSA.CRM_CB_LINEANEGOCIO J ON A.NO_CIA=',VAR_EMPRESA,' AND A.LINEA_NEGOCIO=J.s3s_id
 	LEFT JOIN DSA.CRM_PP_VEHICULOS_INTERESADO K ON K.linea_negocio = J.id  AND NVL(B.SVMAMASTER, C.SVMAMASTER ) = K.SVMAMASTER AND NVL(B.SFX,C.SFX) = K.SFX
	WHERE  A.NO_CIA = ',VAR_EMPRESA,'  AND A.LINEA_NEGOCIO = ',VAR_LINEA_NEGOCIO_1,' AND NVL(A.IND_ANU_DEV,"X")<>"A"
			AND CAST(A.FECHA AS DATE) BETWEEN "',VAR_FECHA_INICIO,'"   AND "',VAR_FECHA_FIN,'" AND A.TIPO_DOC = "FD"
	AND NOT EXISTS (SELECT 1 FROM DSA.S3S_FAC_VENTAS_CAB NC WHERE NC.NO_CIA = A.NO_CIA AND NC.NO_FISICO = A.REFER AND NC.LINEA_NEGOCIO = A.LINEA_NEGOCIO
						AND NC.TIPO_DOC = A.KM AND NC.CENTROD = A.CENTROD 
						AND TO_CHAR(NC.FECHA,"MM/YYYY") = TO_CHAR(A.FECHA,"MM/YYYY"))		
			
			)A
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
	');

		EXECUTE IMMEDIATE VAR_SQL;
		COMMIT;
	
	END;
	



CALL CRG_INT_VENTAS_NUEVOS('DSA','01','2020-01-01','2020-03-11','3');

SELECT * FROM DSA.INT_VENTAS_NUEVOS ; 
SELECT * from DWH.DIM_VEHICULOS_INTERES ;