/* SCRIPT PARA CREAR TABLAS  DEL MODELO DE DATOS PARA NPS */

DROP TABLE IF EXISTS DIM_NPS_CALLCENTER;

CREATE TABLE DIM_NPS_CALLCENTER (
                SK_CALLCENTER bigint(11)  NOT NULL AUTO_INCREMENT,
                COD_CALLCENTER VARCHAR(10) NOT NULL,
                CALL_CENTER VARCHAR(20) NOT NULL,
                FECHA_CARGA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
		 KEY `COD_CALLCENTER` (`COD_CALLCENTER`) /*!90619 USING CLUSTERED COLUMNSTORE */,
  /*!90618 SHARD */ KEY `SK_CALLCENTER` (`SK_CALLCENTER`)
 );

	
-- DESCRIBE DIM_NPS_CALLCENTER ;
INSERT into DIM_NPS_CALLCENTER (COD_CALLCENTER,CALL_CENTER,FECHA_CARGA ) 
SELECT  '1', 'NO DEFINIDO',CURRENT_TIMESTAMP   FROM DUAL ;
-- SELECT * FROM DIM_NPS_CALLCENTER;

/* DROP TABLE IF EXISTS DSA.S3S_CAT_NPS_ESTADO ;
CREATE TABLE DSA.S3S_CAT_NPS_ESTADO ( 
COD_ESTADO bigint(11)  NOT NULL AUTO_INCREMENT,
ESTADO VARCHAR(20) NOT NULL,
 FECHA_CARGA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY `COD_ESTADO` (`COD_ESTADO`) /*!90619 USING CLUSTERED COLUMNSTORE */
/* ) ; */



DROP TABLE IF EXISTS DIM_NPS_ESTADO;
CREATE TABLE DIM_NPS_ESTADO (
                SK_ESTADO bigint(11)  NOT NULL AUTO_INCREMENT,
                --  COD_ESTADO bigint(11) NOT NULL ,
                ESTADO VARCHAR(32) NOT NULL,
                FECHA_CARGA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
		 KEY `SK_ESTADO` (`SK_ESTADO`) /*!90619 USING CLUSTERED COLUMNSTORE */,
  /*!90618 SHARD */ KEY `ESTADO` (`ESTADO`) ) ;
			
			
-- DESCRIBE DIM_NPS_ESTADO ;
INSERT into DIM_NPS_ESTADO (ESTADO,FECHA_CARGA ) 
SELECT   'NO DEFINIDO',CURRENT_TIMESTAMP   FROM DUAL ;
 SELECT * FROM DIM_NPS_ESTADO;

DROP TABLE IF EXISTS DIM_NPS_COMENTARIO;
CREATE TABLE DIM_NPS_COMENTARIO (
                SK_COMENTARIO bigint(11)  NOT NULL AUTO_INCREMENT,
                COMENTARIO VARCHAR(300) NOT NULL,
                FECHA_CARGA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
		 KEY `SK_COMENTARIO` (`SK_COMENTARIO`) /*!90619 USING CLUSTERED COLUMNSTORE */,
  /*!90618 SHARD */ KEY `COMENTARIO` (`COMENTARIO`) ) ;
			
-- DESCRIBE DIM_NPS_COMENTARIO ;
INSERT into DIM_NPS_COMENTARIO (COMENTARIO,FECHA_CARGA) 
SELECT  'NO DEFINIDO',CURRENT_TIMESTAMP   FROM DUAL ;
-- SELECT * FROM DIM_NPS_COMENTARIO;



DROP TABLE IF EXISTS FC_NPS;

 CREATE TABLE FC_NPS (
                SK_EMPRESA int(11) DEFAULT NULL,
                SK_LINEA_NEGOCIO int(11)  NOT NULL ,
                SK_AGENCIA int(11)  NOT NULL ,
                SK_CLIENTE int(11)  NOT NULL ,
                SK_COMENTARIO int(11)  NOT NULL ,
                SK_ESTADO int(11)  NOT NULL ,
                SK_CALLCENTER int(11)  NOT NULL ,
                SK_TECNICO_ASESOR int(11)  NOT NULL ,
                SK_VENDEDOR int(11)  NOT NULL ,
                SK_FECHA_ENVIO int(11)  NOT NULL ,
                SK_FECHA_RESPUESTA int(11)  NOT NULL ,
                SK_FECHA int(11)  NOT NULL ,
                SK_VEHICULO int(11)  NOT NULL ,
                CALIFICACION int(11)  NOT NULL ,
                NUMERO_FACTURA int(11) NOT NULL,
                NUMERO_ORDENSALIDA int(11) NOT NULL,
                -- NUMCBS int(11) NOT NULL,
                ORDEN_REPARACION VARCHAR(32) NOT NULL,               
                KEY SK_EMPRESA (SK_EMPRESA, SK_LINEA_NEGOCIO,SK_AGENCIA, SK_CLIENTE, 
                SK_COMENTARIO ,SK_ESTADO ,SK_CALLCENTER ,SK_TECNICO_ASESOR,SK_VENDEDOR,SK_FECHA_ENVIO, SK_FECHA_RESPUESTA,SK_FECHA )  
                USING CLUSTERED COLUMNSTORE, SHARD KEY (SK_COMENTARIO) );
               
/* CREACION DE LAS TABLAS CATALOGOS/*
 * 
 */









               
              



