 CREATE OR REPLACE PROCEDURE DSA.CRG_DIM_NPS_COMENTARIO(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL) RETURNS void AS
 /***********************************************************************************************************************
  * Descripcion: Cargar Datos DIM_NPS_CALLCENTER
  * Version: 1.0.0
  * Fecha Creacion: 20/01/2020
  * Autor: Byron Vinueza
  * Comentario : Para Ejecutar = CALL CRG_DIM_NPS_COMENTARIO('SQUEMA')
  -------------------------------------------------------------------------
  * Fecha Modificacion:
  * Modificado:
*************************************************************************************************************************/

  DECLARE
	VAR_SQL VARCHAR(4000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN

	START TRANSACTION;
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('DIMENSION',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_DIM_NPS_COMENTARIO'),VAR_DT_INICIO);
	COMMIT;
	
	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_NPS_COMENTARIO ;');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

-- GUARDA EN UNA TABLA TEMPORAL LOS REGISTROS ACTUALIZADOS
	
VAR_SQL=CONCAT('CREATE TABLE ',VAR_SCHEMA,'.TMP1_NPS_COMENTARIO
SELECT   R.SK_COMENTARIO , 
 IF(NVL(P.COMENTARIO,R.COMENTARIO)=R.COMENTARIO,R.COMENTARIO,P.COMENTARIO) COMENTARIO
  ,IF(NVL(P.COMENTARIO,R.COMENTARIO)=R.COMENTARIO,R.FECHA_CARGA,CURRENT_TIMESTAMP) FECHA_CARGA
	FROM DWH.DIM_NPS_COMENTARIO R
	LEFT JOIN  (  SELECT DISTINCT COMENTARIO  FROM ',VAR_SCHEMA,'.S3S_EVA_SEGUIMIENTO_NPS  WHERE COMENTARIO IS NOT NULL 
	 ORDER BY 1  ) P ON R.COMENTARIO=P.COMENTARIO  ;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;


	-- ELIMINA LOS DATOS DE LA DIM
	VAR_SQL=CONCAT('TRUNCATE TABLE DWH.DIM_NPS_COMENTARIO');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;
 

-- INSERTA LOS DATOS DE LA TMP1 A LA DIM
	VAR_SQL=CONCAT('INSERT INTO DWH.DIM_NPS_COMENTARIO
	(SK_COMENTARIO,COMENTARIO,FECHA_CARGA)
	SELECT SK_COMENTARIO,COMENTARIO,FECHA_CARGA
	FROM ' ,VAR_SCHEMA,'.TMP1_NPS_COMENTARIO ;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_NPS_COMENTARIO');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	-- INSERTA NUEVOS REGISTROS A LA DIM 
	VAR_SQL=CONCAT('INSERT INTO DWH.DIM_NPS_COMENTARIO
	(COMENTARIO)
	SELECT A.COMENTARIO
   FROM (SELECT DISTINCT COMENTARIO  FROM ',VAR_SCHEMA,'.S3S_EVA_SEGUIMIENTO_NPS  
 WHERE COMENTARIO IS NOT NULL  ORDER BY COMENTARIO) A
	LEFT JOIN  DWH.DIM_NPS_COMENTARIO  B ON  A.COMENTARIO=B.COMENTARIO
	WHERE B.COMENTARIO IS NULL;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

END;
 SELECT * FROM DWH.DIM_NPS_COMENTARIO dnc;
CALL CRG_DIM_NPS_COMENTARIO('DSA');