 CREATE OR REPLACE PROCEDURE  `CRG_FC_NPS`(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL,  VAR_FECHA_INICIO date NULL, VAR_FECHA_FIN date NULL) RETURNS void AS
/***********************************************************************************************************************
  * Descripcion: Cargar Datos FC_TALLERES
  * Version: 1.0.0
  * Fecha Creacion: 24/07/2019
  * Autor: BYRON VINUEZA
  * Comentario : Para Ejecutar = CALL CRG_FC_NPS(DSA,FI,FF) 
  -------------------------------------------------------------------------
  * Fecha Modificacion:
  * Modificado:
*************************************************************************************************************************/
DECLARE
	VAR_SQL VARCHAR(4000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN
START TRANSACTION;
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('TABLA DE HECHOS',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_FC_NPS'),VAR_DT_INICIO);
	COMMIT;

	VAR_SQL=CONCAT('DELETE FROM DWH.FC_NPS A 
					WHERE SK_FECHA >= (SELECT SK_FECHA FROM DWH.DIM_FECHA WHERE FECHA = "',VAR_FECHA_INICIO,'") 
					AND SK_FECHA <= (SELECT SK_FECHA FROM DWH.DIM_FECHA WHERE FECHA = "',VAR_FECHA_FIN,'") ') ;
	EXECUTE IMMEDIATE VAR_SQL;			
	COMMIT;

		VAR_SQL=CONCAT(' INSERT INTO DWH.FC_NPS
  SELECT 
  NVL(CIA.SK_EMPRESA,1) SK_EMPRESA,
  NVL(LIN.SK_LINEA_NEGOCIO,1) SK_LINEA_NEGOCIO  , 
  NVL(AG.SK_AGENCIA,1) SK_AGENCIA ,
  NVL(CL.SK_CLIENTE,1) SK_CLIENTE,
  NVL(CO.SK_COMENTARIO,1) SK_COMENTARIO ,
  NVL(ET.SK_ESTADO,1) SK_ESTADO ,
  NVL(CA.SK_CALLCENTER,1) SK_CALLCENTER ,
  NVL(TA.SK_TECNICO_ASESOR,1) SK_TECNICO_ASESOR ,
  NVL(VEN.SK_VENDEDOR,1) SK_VENDEDOR ,
  NVL(DF.SK_FECHA,"19700101")  SK_FECHA_ENVIO, 
  NVL(DFC.SK_FECHA,"19700101")  SK_FECHA_RESPUESTA ,
  NVL(FM.SK_FECHA,"19700101") SK_FECHA ,
  NVL(VH.SK_VEHICULO,1) SK_VEHICULO ,
  NVL(NPS.CALIFICACION,0) CALIFICACION,
  NVL(NPS.FACTURA_NO,1) NUMERO_FACTURA ,
  NVL(NPS.ORDENSAL_NO,1) NUMERO_ORDENSALIDA ,
  -- NVL(NPS.NUMCBS,1) NUMCBS,
  NVL(NPS.ORDENREP_ID,1)  ORDEN_REPARACION
  FROM DSA.S3S_EVA_SEGUIMIENTO_NPS NPS 
  LEFT JOIN DWH.DIM_EMPRESA CIA ON CIA.COD_EMPRESA = NPS.NO_CIA 
  LEFT JOIN DWH.DIM_LINEA_NEGOCIO LIN ON LIN.COD_LINEA_NEGOCIO=NPS.LINEA_NEGOCIO AND NPS.NO_CIA=LIN.COD_EMPRESA
  LEFT JOIN  DWH.DIM_AGENCIA AG ON NPS.CODIGO=AG.COD_AGENCIA AND NPS.NO_CIA=AG.COD_EMPRESA 
  LEFT JOIN DWH.DIM_CLIENTE CL ON NPS.NO_CLIENTE_PRO = CL.COD_CLIENTE AND NPS.NO_CIA=CL.COD_EMPRESA
  LEFT JOIN DWH.DIM_NPS_COMENTARIO CO ON CO.COMENTARIO=NPS.COMENTARIO 
  LEFT JOIN DWH.DIM_NPS_ESTADO ET ON ET.ESTADO=NPS.ESTADO
  LEFT JOIN DWH.DIM_NPS_CALLCENTER CA ON CA.COD_CALLCENTER=NPS.CALLCENTER 
  LEFT JOIN DWH.DIM_TECNICO_ASESOR TA ON TA.COD_TECNICO_ASESOR=NPS.TECNIASESOR_ID AND TA.COD_EMPRESA=NPS.NO_CIA
  LEFT JOIN DWH.DIM_VENDEDOR VEN ON VEN.COD_EMPRESA=NPS.NO_CIA AND VEN.COD_VENDEDOR=NPS.TECNIASESOR_ID 
  LEFT JOIN DWH.DIM_FECHA DF ON  DATE(DF.FECHA)=DATE(NPS.FECHA_ENVIO_MAIL) 
  LEFT JOIN DWH.DIM_FECHA DFC ON  DATE(DFC.FECHA)=DATE(NPS.FECHA_MODIFICACION) 
  LEFT JOIN DWH.DIM_FECHA FM ON  DATE(FM.FECHA)=DATE(NPS.FECHA_CREACION) 
  LEFT JOIN DWH.DIM_VEHICULO VH ON VH.COD_EMPRESA=NPS.NO_CIA AND VH.COD_LINEA_NEGOCIO=NPS.LINEA_NEGOCIO AND VH.CHASIS=NPS.CHASIS
  WHERE				DATE(NPS.FECHA_CREACION ) >= "',VAR_FECHA_INICIO,'" AND
				DATE(NPS.FECHA_CREACION ) <= "',VAR_FECHA_FIN,'"  ') ;
	EXECUTE IMMEDIATE VAR_SQL;	
	COMMIT;
END;


SELECT * FROM DWH.FC_NPS fn;
SELECT COUNT(*) FROM DSA.S3S_EVA_SEGUIMIENTO_NPS ssesn;


call CRG_DIM_NPS_CALLCENTER('DSA') ;
CALL CRG_DIM_NPS_COMENTARIO('DSA') ;
CALL CRG_DIM_NPS_ESTADO('DSA');
CALL CRG_FC_NPS('DSA','2019-01-01','2020-01-30') ;

SELECT * from S3S_EVA_SEGUIMIENTO_NPS where CODIGO is null;

SELECT *  from S3S_EVA_SEGUIMIENTO_NPS;



DROP PROCEDURE DWH.CRG_FC_NPS;

