 CREATE OR REPLACE PROCEDURE DSA.CRG_DIM_NPS_CALLCENTER(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL) RETURNS void AS
 /***********************************************************************************************************************
  * Descripcion: Cargar Datos DIM_NPS_CALLCENTER
  * Version: 1.0.0
  * Fecha Creacion: 20/01/2020
  * Autor: Byron Vinueza
  * Comentario : Para Ejecutar = CALL CRG_DIM_NPS_CALLCENTER('SQUEMA')
  -------------------------------------------------------------------------
  * Fecha Modificacion:
  * Modificado:
*************************************************************************************************************************/
 DECLARE
	VAR_SQL VARCHAR(4000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN

		START TRANSACTION;
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('DIMENSION',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_DIM_NPS_CALLCENTER'),VAR_DT_INICIO);
	COMMIT;
	
	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_NPS_CALLCENTER');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;


	-- GUARDA EN UNA TABLA TEMPORAL LOS REGISTROS ACTUALIZADOS
	
VAR_SQL=CONCAT('CREATE TABLE ',VAR_SCHEMA,'.TMP1_NPS_CALLCENTER
		SELECT  R.SK_CALLCENTER,R.COD_CALLCENTER
	,IF(NVL(P.CALLCENTER,R.CALL_CENTER)=R.CALL_CENTER,R.CALL_CENTER,P.CALLCENTER) CALL_CENTER
     ,IF(NVL(P.CALLCENTER,R.CALL_CENTER)=R.CALL_CENTER,R.FECHA_CARGA,CURRENT_TIMESTAMP) FECHA_CARGA
	FROM DWH.DIM_NPS_CALLCENTER R
	LEFT JOIN ' ,VAR_SCHEMA,'.S3S_CAT_NPS_CALLCENTER P ON R.COD_CALLCENTER=P.COD_CALLCENTER  ;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	-- ELIMINA LOS DATOS DE LA DIM
	VAR_SQL=CONCAT('TRUNCATE TABLE DWH.DIM_NPS_CALLCENTER');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

-- INSERTA LOS DATOS DE LA TMP1 A LA DIM
	VAR_SQL=CONCAT('INSERT INTO DWH.DIM_NPS_CALLCENTER
	(SK_CALLCENTER,COD_CALLCENTER,CALL_CENTER,FECHA_CARGA)
	SELECT SK_CALLCENTER,COD_CALLCENTER,CALL_CENTER,FECHA_CARGA
	FROM ' ,VAR_SCHEMA,'.TMP1_NPS_CALLCENTER ;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_NPS_CALLCENTER');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	-- INSERTA NUEVOS REGISTROS A LA DIM 
	VAR_SQL=CONCAT('INSERT INTO DWH.DIM_NPS_CALLCENTER
	(COD_CALLCENTER,CALL_CENTER)
SELECT A.COD_CALLCENTER ,  A.CALLCENTER CALL_CENTER  
   FROM ',VAR_SCHEMA,'.S3S_CAT_NPS_CALLCENTER A
	LEFT JOIN DWH.DIM_NPS_CALLCENTER B ON  A.COD_CALLCENTER=B.COD_CALLCENTER
	WHERE B.COD_CALLCENTER IS NULL;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

END;
-- SELECT * FROM DWH.DIM_NPS_CALLCENTER;
CALL CRG_DIM_NPS_CALLCENTER('DSA');
