CREATE VIEW VW_NPS AS   SELECT B.EMPRESA , C.LINEA_NEGOCIO ,D.AGENCIA ,E.ESTADO, F.CALL_CENTER,
CASE WHEN G.SK_TECNICO_ASESOR = 1 THEN H.NOMBRE_VENDEDOR ELSE G.TECNICO_ASESOR END AS ASESOR,
I.FECHA FECHA_CREACION , I.FECHA FECHA_ENVIO,J.FECHA FECHA_RESPUESTA,
L.NOMBRE,L.TELEFONO,L.TELEFONO2,L.EMAIL1,L.EMAIL2,
A.CALIFICACION,M.COMENTARIO,
A.NUMERO_FACTURA 
FROM FC_NPS A 
left join  DIM_EMPRESA B ON A.SK_EMPRESA=B.SK_EMPRESA
LEFT JOIN DIM_LINEA_NEGOCIO C ON A.SK_LINEA_NEGOCIO=C.SK_LINEA_NEGOCIO
LEFT JOIN DIM_AGENCIA D ON A.SK_AGENCIA=D.SK_AGENCIA 
LEFT JOIN DIM_NPS_ESTADO E ON A.SK_ESTADO = E.SK_ESTADO  
LEFT JOIN DIM_NPS_CALLCENTER F ON F.SK_CALLCENTER=A.SK_CALLCENTER 
LEFT JOIN DIM_TECNICO_ASESOR G ON A.SK_TECNICO_ASESOR=G.SK_TECNICO_ASESOR
LEFT JOIN DIM_VENDEDOR H ON H.SK_VENDEDOR=A.SK_VENDEDOR 
LEFT JOIN DIM_FECHA I ON A.SK_FECHA = I.SK_FECHA 
LEFT JOIN DIM_FECHA J ON A.SK_FECHA_ENVIO = J.SK_FECHA 
LEFT JOIN DIM_FECHA K ON A.SK_FECHA_RESPUESTA = K.SK_FECHA 
LEFT JOIN DIM_CLIENTE L ON A.SK_CLIENTE=L.SK_CLIENTE
LEFT JOIN DIM_NPS_COMENTARIO M ON A.SK_COMENTARIO = M.SK_COMENTARIO
; 
-- WHERE H.SK_VENDEDOR=1 AND G.SK_TECNICO_ASESOR =1;

SELECT * FROM FC_NPS fn;

SELECT * FROM VW_NPS;

drop VIEW VW_NPS;

SELECT * FROM DIM_TIPO_FINANCIACION dtf WHERE COD_TIPO_FINANCIACION LIKE 'C%' AND ;


SELECT * FROM FC_VENTAS_NUEVOS fvn;