DROP TABLE FC_VENTAS_EXONERADOS;
CREATE TABLE `FC_VENTAS_EXONERADOS` (
  `SK_FECHA_FACTURA` longtext CHARACTER SET utf8 COLLATE utf8_general_ci,
  `SK_EMPRESA` bigint(20) DEFAULT NULL,
  `SK_LINEA_NEGOCIO` bigint(20) DEFAULT NULL,
  `SK_AGENCIA` bigint(20) DEFAULT NULL,
  `SK_TIPO_DOCUMENTO` bigint(20) DEFAULT NULL,
  `SK_VENDEDOR` bigint(20) DEFAULT NULL,
  `SK_VERSION_VEHICULO` bigint(20) DEFAULT NULL,
  `SK_FORMA_PAGO` bigint(20) DEFAULT NULL,
  `SK_VEHICULO` bigint(20) DEFAULT NULL,
  `SK_CLIENTE` bigint(20) DEFAULT NULL,
  `SK_CLASE_CLIENTE` bigint(20) DEFAULT NULL,
  `SK_TIPO_FINANCIACION` bigint(20) DEFAULT NULL,
  `SK_COTIZACION` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `SK_NO_FISICO` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `SK_FACTURA` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
   SK_TIPO_EXONERADO bigint(20) DEFAULT NULL,
   PORCENTAJE_DISCAPACIDAD bigint(20) DEFAULT NULL,
  `COSTO_VEHICULO` double DEFAULT NULL,
  `DESCUENTO` double DEFAULT NULL,
  `PRECIO` double DEFAULT NULL,
  `SALDO_FINANCIAR` decimal(39,2) DEFAULT 0,
  `CUOTA_DE_ALCANCE` decimal(39,2) DEFAULT 0,
  COSTOS_IMPORT decimal(39,2) DEFAULT 0, 
  COMISON_SIN_IVA decimal(39,2) DEFAULT 0,
  COMISION_CON_IVA  decimal(39,2) DEFAULT 0,
  KEY `SK_EMPRESA` (`SK_EMPRESA`,`SK_LINEA_NEGOCIO`,`SK_AGENCIA`,`SK_TIPO_DOCUMENTO`,`SK_VENDEDOR`,`SK_VERSION_VEHICULO`,`SK_FORMA_PAGO`,`SK_VEHICULO`,`SK_CLIENTE`,`SK_CLASE_CLIENTE`,`SK_TIPO_FINANCIACION`,`SK_COTIZACION`,`SK_NO_FISICO`,`SK_FACTURA`) /*!90619 USING CLUSTERED COLUMNSTORE */,
  /*!90618 SHARD */ KEY `SK_FACTURA` (`SK_FACTURA`)
) ;

DROP TABLE FC_VENTAS_EXONERADOS;
DROP VIEW VW_VEHICULOS_EXONERADOS;

CALL CRG_INT_VENTAS_EXONERADOS('DSA','01','2020-01-01','2020-01-31','70'); 
CALL CRG_FC_VENTAS_EXONERADOS('DSA','01','2020-01-01','2020-02-03');


INSERT INTO DWH.FC_VENTAS_EXONERADOS
		SELECT NVL(M.SK_FECHA,"19700101") AS SK_FECHA_FACTURA, NVL(B.SK_EMPRESA,1)SK_EMPRESA, NVL(C.SK_LINEA_NEGOCIO,1)SK_LINEA_NEGOCIO, NVL(D.SK_AGENCIA,1)SK_AGENCIA,  
		NVL(E.SK_TIPO_DOCUMENTO,1)SK_TIPO_DOCUMENTO, NVL(F.SK_VENDEDOR,1)SK_VENDEDOR, NVL(G.SK_VERSION_VEHICULO,1)SK_VERSION_VEHICULO, NVL(H.SK_FORMA_PAGO, 1)SK_FORMA_PAGO,
		NVL(I.SK_VEHICULO,1)SK_VEHICULO, NVL(J.SK_CLIENTE, 1)SK_CLIENTE, NVL(K.SK_CLASE_CLIENTE,1)SK_CLASE_CLIENTE, NVL(L.SK_TIPO_FINANCIACION,1)SK_TIPO_FINANCIACION,
		NVL(A.COD_COTIZACION,"NO DFINIDO") AS SK_COTIZACION, NVL(A.COD_NO_FISICO,"NO DEFINIDO") AS SK_NO_FISICO, NVL(A.COD_FACTURA,"NO DEFINIDO") AS SK_FACTURA, 
		NVL(A.COSTO_VEHICULO,0)COSTO_VEHICULO, NVL(A.DESCUENTO,0)DESCUENTO, NVL(A.PRECIO,0)PRECIO, NVL(A.SUBTOTAL_MASIVO,0)SUBTOTAL_MASIVO,
		NVL(A.UTILIDAD,0) UTILIDAD, NVL(A.VALOR_NETO,0) VALOR_NETO, NVL(SALDO_FINANCIAR,0) AS SALDO_FINANCIAR, NVL(CUOTA_DE_ALCANCE,0) AS CUOTA_DE_ALCANCE
		FROM DSA.INT_VENTAS_NUEVOS A
		LEFT JOIN DWH.DIM_EMPRESA B ON A.COD_EMPRESA = B.COD_EMPRESA
		LEFT JOIN DWH.DIM_LINEA_NEGOCIO C ON A.COD_EMPRESA = C.COD_EMPRESA AND A.COD_LINEA_NEGOCIO = C.COD_LINEA_NEGOCIO
		LEFT JOIN DWH.DIM_AGENCIA D ON A.COD_EMPRESA = D.COD_EMPRESA AND A.COD_AGENCIA = D.COD_AGENCIA
		LEFT JOIN DWH.DIM_TIPO_DOCUMENTO E ON A.COD_EMPRESA = E.COD_EMPRESA AND A.COD_TIPO_DOCUMENTO = E.COD_TIPO_DOCUMENTO 
		LEFT JOIN DWH.DIM_VENDEDOR F ON A.COD_EMPRESA = F.COD_EMPRESA AND A.COD_VENDEDOR = F.COD_VENDEDOR
		LEFT JOIN DWH.DIM_VERSION_VEHICULO G ON A.COD_EMPRESA = G.COD_EMPRESA AND A.COD_VERSION_VEHICULO = G.COD_VERSION_VEHICULO
		LEFT JOIN DWH.DIM_FORMA_PAGO H ON A.COD_TIPO_FORMA_PAGO = H.COD_FORMA_PAGO
		LEFT JOIN DWH.DIM_VEHICULO I ON A.COD_EMPRESA = I.COD_EMPRESA AND A.COD_CHASIS = I.CHASIS AND A.COD_LINEA_NEGOCIO = I.COD_LINEA_NEGOCIO
		LEFT JOIN DWH.DIM_CLIENTE J ON A.COD_EMPRESA = J.COD_EMPRESA AND A.COD_CLIENTE = J.COD_CLIENTE
		LEFT JOIN DWH.DIM_CLASE_CLIENTE K ON A.COD_EMPRESA = K.COD_EMPRESA AND A.COD_CLASE_CLIENTE = K.COD_CLASE_CLIENTE AND K.COD_LINEA_NEGOCIO = "VEH" 
		LEFT JOIN DWH.DIM_TIPO_FINANCIACION L ON A.COD_EMPRESA = L.COD_EMPRESA AND A.COD_ENTIDAD = L.COD_TIPO_FINANCIACION 
		LEFT JOIN DWH.DIM_FECHA M ON CAST(A.FECHA_FACTURA AS DATE) = M.FECHA ;
	
	SELECT COUTA_DE_ALCANCE FROM INT_VENTAS_NUEVOS;

