   CREATE OR REPLACE PROCEDURE `CRG_FC_VENTAS_EXONERADOS`(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_EMPRESA varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_FECHA_INICIO date NULL, VAR_FECHA_FIN date NULL) RETURNS void AS
/***********************************************************************************************************************
  * Descripcion: Cargar Datos FC_TALLERES
  * Version: 1.0.0
  * Fecha Creacion: 24/07/2019
  * Autor: Viviana Herrera
  * Comentario : Para Ejecutar = CALL CRG_FC_VENTAS_EXONERADOS('SQUEMA', 'EMPRESA', 'FECHA_INICIO', 'FECHA_FIN','LINEA_NEGOCIO')
  -------------------------------------------------------------------------
  * Fecha Modificacion:
  * Modificado:
*************************************************************************************************************************/
DECLARE
	VAR_SQL VARCHAR(4000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN
START TRANSACTION;
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('TABLA DE HECHOS',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_FC_VENTAS_EXONERADOS'),VAR_DT_INICIO);
	COMMIT;

	VAR_SQL=CONCAT('DELETE FROM DWH.FC_VENTAS_EXONERADOS A 
					WHERE A.SK_EMPRESA = (SELECT SK_EMPRESA FROM DWH.DIM_EMPRESA WHERE COD_EMPRESA = ',VAR_EMPRESA,')
					AND SK_FECHA_FACTURA >= (SELECT SK_FECHA FROM DWH.DIM_FECHA WHERE FECHA = "',VAR_FECHA_INICIO,'") 
					AND SK_FECHA_FACTURA <= (SELECT SK_FECHA FROM DWH.DIM_FECHA WHERE FECHA = "',VAR_FECHA_FIN,'") ') ;
	EXECUTE IMMEDIATE VAR_SQL;			
	COMMIT;

		VAR_SQL=CONCAT('INSERT INTO DWH.FC_VENTAS_EXONERADOS
		SELECT NVL(M.SK_FECHA,"19700101") AS SK_FECHA_FACTURA, NVL(B.SK_EMPRESA,1)SK_EMPRESA, NVL(C.SK_LINEA_NEGOCIO,1)SK_LINEA_NEGOCIO, NVL(D.SK_AGENCIA,1)SK_AGENCIA,  
		NVL(E.SK_TIPO_DOCUMENTO,1)SK_TIPO_DOCUMENTO, NVL(F.SK_VENDEDOR,1)SK_VENDEDOR, NVL(G.SK_VERSION_VEHICULO,1)SK_VERSION_VEHICULO, NVL(H.SK_FORMA_PAGO, 1)SK_FORMA_PAGO,
		NVL(I.SK_VEHICULO,1)SK_VEHICULO, NVL(J.SK_CLIENTE, 1)SK_CLIENTE, NVL(K.SK_CLASE_CLIENTE,1)SK_CLASE_CLIENTE, NVL(L.SK_TIPO_FINANCIACION,1)SK_TIPO_FINANCIACION,
		NVL(A.COD_COTIZACION,"NO DFINIDO") AS SK_COTIZACION, NVL(A.COD_NO_FISICO,"NO DEFINIDO") AS SK_NO_FISICO, NVL(A.COD_FACTURA,"NO DEFINIDO") AS SK_FACTURA, 
		N.SK_TIPO_EXONERADO, NVL(PORCENTAJE_DISCAPACIDAD,0) PORCENTAJE_DISCAPACIDAD,
		NVL(A.COSTO_VEHICULO,0)COSTO_VEHICULO, NVL(A.DESCUENTO,0)DESCUENTO, NVL(A.PRECIO,0)PRECIO,
		 NVL(SALDO_FINANCIAR,0) AS SALDO_FINANCIAR, NVL(CUOTA_DE_ALCANCE,0) AS CUOTA_DE_ALCANCE,
		 NVL(COSTOS_IMPORT,0 ) AS COSTOS_IMPORT , NVL(COMISON_SIN_IVA,0) AS COMISON_SIN_IVA , NVL(COMISION_CON_IVA,0) AS COMISION_CON_IVA
         FROM DSA.INT_VENTAS_EXONERADOS A
		LEFT JOIN DWH.DIM_EMPRESA B ON A.COD_EMPRESA = B.COD_EMPRESA
		LEFT JOIN DWH.DIM_LINEA_NEGOCIO C ON A.COD_EMPRESA = C.COD_EMPRESA AND A.COD_LINEA_NEGOCIO = C.COD_LINEA_NEGOCIO
		LEFT JOIN DWH.DIM_AGENCIA D ON A.COD_EMPRESA = D.COD_EMPRESA AND A.COD_AGENCIA = D.COD_AGENCIA
		LEFT JOIN DWH.DIM_TIPO_DOCUMENTO E ON A.COD_EMPRESA = E.COD_EMPRESA AND A.COD_TIPO_DOCUMENTO = E.COD_TIPO_DOCUMENTO 
		LEFT JOIN DWH.DIM_VENDEDOR F ON A.COD_EMPRESA = F.COD_EMPRESA AND A.COD_VENDEDOR = F.COD_VENDEDOR
		LEFT JOIN DWH.DIM_VERSION_VEHICULO G ON A.COD_EMPRESA = G.COD_EMPRESA AND A.COD_VERSION_VEHICULO = G.COD_VERSION_VEHICULO
		LEFT JOIN DWH.DIM_FORMA_PAGO H ON A.COD_TIPO_FORMA_PAGO = H.COD_FORMA_PAGO
		LEFT JOIN DWH.DIM_VEHICULO I ON A.COD_EMPRESA = I.COD_EMPRESA AND A.COD_CHASIS = I.CHASIS AND A.COD_LINEA_NEGOCIO = I.COD_LINEA_NEGOCIO
		LEFT JOIN DWH.DIM_CLIENTE J ON A.COD_EMPRESA = J.COD_EMPRESA AND A.COD_CLIENTE = J.COD_CLIENTE
		LEFT JOIN DWH.DIM_CLASE_CLIENTE K ON A.COD_EMPRESA = K.COD_EMPRESA AND A.COD_CLASE_CLIENTE = K.COD_CLASE_CLIENTE AND K.COD_LINEA_NEGOCIO = "VEH" 
		LEFT JOIN DWH.DIM_TIPO_FINANCIACION L ON A.COD_EMPRESA = L.COD_EMPRESA AND A.COD_ENTIDAD = L.COD_TIPO_FINANCIACION 
		LEFT JOIN DWH.DIM_FECHA M ON CAST(A.FECHA_FACTURA AS DATE) = M.FECHA
	    LEFT JOIN DWH.DIM_TIPO_EXONERADO N ON N.COD_TIPO_EXONERADO=A.COD_TIPO_EXONERADO
		WHERE 
				CAST(A.FECHA_FACTURA AS DATE) >= "',VAR_FECHA_INICIO,'" AND
				CAST(A.FECHA_FACTURA AS DATE) <= "',VAR_FECHA_FIN,'"  AND
				A.COD_EMPRESA = ',VAR_EMPRESA,'
		') ;
	EXECUTE IMMEDIATE VAR_SQL;	
	COMMIT;
END;




 CREATE VIEW `VW_VEHICULOS_NUEVOS` AS 
 SELECT `B`.`FECHA` AS `FECHA`, `C`.`COD_EMPRESA` AS `COD_EMPRESA`, 
 `C`.`EMPRESA` AS `EMPRESA`, `D`.`COD_LINEA_NEGOCIO` AS `COD_LINEA_NEGOCIO`, 
 `D`.`LINEA_NEGOCIO` AS `LINEA_NEGOCIO`, `E`.`COD_AGENCIA` AS `COD_AGENCIA`, 
 `E`.`AGENCIA` AS `AGENCIA`, `F`.`COD_TIPO_DOCUMENTO` AS `COD_TIPO_DOCUMENTO`, 
 `F`.`TIPO_DOCUMENTO` AS `TIPO_DOCUMENTO`, `G`.`COD_USUARIO` AS `COD_USUARIO`,
 `G`.`NOMBRE_VENDEDOR` AS `NOMBRE_VENDEDOR`, `H`.`COD_VERSION_VEHICULO` AS `COD_VERSION_VEHICULO`,
 `H`.`VERSION_VEHICULO` AS `VERSION_VEHICULO`, `I`.`FORMA_PAGO` AS `FORMA_PAGO`, 
 `J`.`CHASIS` AS `CHASIS`, `J`.`MARCA` AS `MARCA`, `J`.`MODELO` AS `MODELO`,
 `J`.`PLACA` AS `PLACA`, `J`.`SFX` AS `SFX`, `J`.`ANIO_VEHICULO` AS `ANIO_VEHICULO`, 
 `K`.`NOMBRE` AS `NOMBRE`, `K`.`CEDULA` AS `CEDULA`, `K`.`PROVINCIA` AS `PROVINCIA`, 
 `K`.`SEXO` AS `SEXO`, `K`.`TELEFONO` AS `TELEFONO`, `K`.`TELEFONO2` AS `TELEFONO2`, 
 `K`.`TIPO_CLIENTE` AS `TIPO_CLIENTE`, `L`.`COD_TIPO_FINANCIACION` AS `COD_TIPO_FINANCIACION`,
 `L`.`TIPO_FINANCIACION` AS `TIPO_FINANCIACION`, `A`.`COSTO_VEHICULO` AS `COSTO_VEHICULO`, 
 `A`.`DESCUENTO` AS `DESCUENTO`, `A`.`PRECIO` AS `PRECIO`, `A`.`SUBTOTAL_MASIVO` AS `SUBTOTAL_MASIVO`, 
 `A`.`VALOR_NETO` AS `VALOR_NETO`, `A`.`SALDO_FINANCIAR` AS `SALDO_FINANCIAR`,
 `A`.`COUTA_DE_ALCANCE` AS `COUTA_DE_ALCANCE`, `A`.`UTILIDAD` AS `UTILIDAD`, 
 `A`.`SK_FACTURA` AS `NRO_FACTURA`, `A`.`SK_COTIZACION` AS `NRO_COTIZACION`, 
 `A`.`SK_NO_FISICO` AS `NRO_FISICO` 
 FROM (((((((((((`FC_VENTAS_NUEVOS` as `A`  
 LEFT  JOIN `DIM_FECHA` as `B`  ON (`A`.`SK_FECHA_FACTURA` = `B`.`SK_FECHA`)) 
 LEFT  JOIN `DIM_EMPRESA` as `C`  ON (`A`.`SK_EMPRESA` = `C`.`SK_EMPRESA`)) 
 LEFT  JOIN `DIM_LINEA_NEGOCIO` as `D`  ON (`A`.`SK_LINEA_NEGOCIO` = `D`.`SK_LINEA_NEGOCIO`)) 
 LEFT  JOIN `DIM_AGENCIA` as `E`  ON (`A`.`SK_AGENCIA` = `E`.`SK_AGENCIA`)) 
 LEFT  JOIN `DIM_TIPO_DOCUMENTO` as `F`  ON (`A`.`SK_TIPO_DOCUMENTO` = `F`.`SK_TIPO_DOCUMENTO`)) 
 LEFT  JOIN `DIM_VENDEDOR` as `G`  ON (`A`.`SK_VENDEDOR` = `G`.`SK_VENDEDOR`)) 
 LEFT  JOIN `DIM_VERSION_VEHICULO` as `H`  ON (`A`.`SK_VERSION_VEHICULO` = `H`.`SK_VERSION_VEHICULO`)) 
 LEFT  JOIN `DIM_FORMA_PAGO` as `I`  ON (`A`.`SK_FORMA_PAGO` = `I`.`SK_FORMA_PAGO`)) 
 LEFT  JOIN `DIM_VEHICULO` as `J`  ON (`A`.`SK_VEHICULO` = `J`.`SK_VEHICULO`)) 
 LEFT  JOIN `DIM_CLIENTE` as `K`  ON (`A`.`SK_CLIENTE` = `K`.`SK_CLIENTE`)) 
 LEFT  JOIN `DIM_TIPO_FINANCIACION` as `L`  ON (`A`.`SK_TIPO_FINANCIACION` = `L`.`SK_TIPO_FINANCIACION`));

CREATE VIEW VW_VEHICULOS_EXONERADOS  AS 
SELECT B.FECHA , C.EMPRESA , D.LINEA_NEGOCIO,
E.AGENCIA, F.NOMBRE_VENDEDOR, G.TIPO_DOCUMENTO ,G.COD_TIPO_DOCUMENTO ,
H.VERSION_VEHICULO , I.FORMA_PAGO ,A.SK_FACTURA , A.SK_COTIZACION, A.SK_NO_FISICO , J.CHASIS, J.MODELO ,
K.CEDULA , M.TIPO_EXONERADO ,A.PORCENTAJE_DISCAPACIDAD , L.TIPO_FINANCIACION , L.COD_TIPO_FINANCIACION ,
A.COSTO_VEHICULO , A.PRECIO , A.SALDO_FINANCIAR , A.CUOTA_DE_ALCANCE ,A.COSTOS_IMPORT ,A.COMISON_SIN_IVA , A.COMISION_CON_IVA
FROM FC_VENTAS_EXONERADOS A 
LEFT JOIN DIM_FECHA B ON A.SK_FECHA_FACTURA=B.SK_FECHA
LEFT JOIN DIM_EMPRESA C ON A.SK_EMPRESA=C.SK_EMPRESA
LEFT JOIN DIM_LINEA_NEGOCIO D ON A.SK_LINEA_NEGOCIO=D.SK_LINEA_NEGOCIO
LEFT JOIN DIM_AGENCIA E ON A.SK_AGENCIA = E.SK_AGENCIA 
LEFT JOIN DIM_VENDEDOR F ON A.SK_VENDEDOR=F.SK_VENDEDOR
LEFT JOIN DIM_TIPO_DOCUMENTO G ON A.SK_TIPO_DOCUMENTO=G.SK_TIPO_DOCUMENTO
LEFT JOIN DIM_VERSION_VEHICULO H ON A.SK_VERSION_VEHICULO=H.SK_VERSION_VEHICULO
LEFT JOIN DIM_FORMA_PAGO I ON A.SK_FORMA_PAGO = I.SK_FORMA_PAGO
LEFT JOIN DIM_VEHICULO J ON A.SK_VEHICULO = J.SK_VEHICULO
LEFT JOIN DIM_CLIENTE K ON A.SK_CLIENTE = K.SK_CLIENTE
LEFT JOIN DIM_TIPO_FINANCIACION L ON A.SK_TIPO_FINANCIACION = L.SK_TIPO_FINANCIACION
LEFT JOIN DIM_TIPO_EXONERADO M ON A.SK_TIPO_EXONERADO=M.SK_TIPO_EXONERADO ;


