 CREATE OR REPLACE PROCEDURE CRG_DIM_TIPO_EXONERADO(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL) RETURNS void AS
 /***********************************************************************************************************************
  * Descripcion: Cargar Datos DIM_TIPO_EXONERADO
  * Version: 1.0.0
  * Fecha Creacion: 04/02/2020
  * Autor: Byron Vinueza
  * Comentario : Para Ejecutar = CALL CRG_DIM_TIPO_EXONERADO('SQUEMA')
  -------------------------------------------------------------------------
  * Fecha Modificacion:
  * Modificado:
*************************************************************************************************************************/

  DECLARE
	VAR_SQL VARCHAR(4000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN
	

	START TRANSACTION;
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('DIMENSION',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_DIM_TIPO_EXONERADO'),VAR_DT_INICIO);
	COMMIT;
	
	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_TIPO_EXONERADO ;');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

-- GUARDA EN UNA TABLA TEMPORAL LOS REGISTROS ACTUALIZADOS
	
VAR_SQL=CONCAT('CREATE TABLE ',VAR_SCHEMA,'.TMP1_TIPO_EXONERADO
SELECT   R.SK_TIPO_EXONERADO ,
 IF(NVL(P.ID_TIPO_EXONERADO,R.COD_TIPO_EXONERADO)=R.COD_TIPO_EXONERADO,R.COD_TIPO_EXONERADO,P.ID_TIPO_EXONERADO) COD_TIPO_EXONERADO,
  IF(NVL(P.TIPO_EXONERADO,R.TIPO_EXONERADO)=R.TIPO_EXONERADO,R.TIPO_EXONERADO,P.TIPO_EXONERADO) TIPO_EXONERADO,
   IF(NVL(P.ID_TIPO_EXONERADO,R.COD_TIPO_EXONERADO)=R.COD_TIPO_EXONERADO,R.COD_TIPO_EXONERADO,CURRENT_TIMESTAMP) FECHA_CARGA
	FROM DWH.DIM_TIPO_EXONERADO R
	LEFT JOIN  ',VAR_SCHEMA,'.S3S_CAT_TIPO_EXONERADO P ON R.COD_TIPO_EXONERADO=P.ID_TIPO_EXONERADO ;

	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	-- ELIMINA LOS DATOS DE LA CAT
	VAR_SQL=CONCAT('TRUNCATE TABLE DWH.DIM_TIPO_EXONERADO ');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;
 
-- INSERTA LOS DATOS DE LA TMP1 A LA CAT
	VAR_SQL=CONCAT('INSERT INTO DWH.DIM_TIPO_EXONERADO
	(SK_TIPO_EXONERADO,COD_TIPO_EXONERADO,TIPO_EXONERADO,FECHA_CARGA)
	SELECT SK_TIPO_EXONERADO,COD_TIPO_EXONERADO,TIPO_EXONERADO,FECHA_CARGA
	FROM ' ,VAR_SCHEMA,'.TMP1_TIPO_EXONERADO ;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_TIPO_EXONERADO');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	-- INSERTA NUEVOS REGISTROS A LA CAT 
	VAR_SQL=CONCAT('INSERT INTO DWH.DIM_TIPO_EXONERADO
	(COD_TIPO_EXONERADO,TIPO_EXONERADO)
	SELECT A.ID_TIPO_EXONERADO AS COD_TIPO_EXONERADO , A.TIPO_EXONERADO 
   FROM ',VAR_SCHEMA,'.S3S_CAT_TIPO_EXONERADO A
	LEFT JOIN  DWH.DIM_TIPO_EXONERADO B ON  A.ID_TIPO_EXONERADO=B.COD_TIPO_EXONERADO
	WHERE B.COD_TIPO_EXONERADO IS NULL ORDER BY 1;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

END;

CALL CRG_DIM_TIPO_EXONERADO('DSA');

SELECT * FROM DWH.DIM_TIPO_EXONERADO;

