 CREATE OR REPLACE PROCEDURE CRG_CAT_TIPO_EXONERADO(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL) RETURNS void AS
 /***********************************************************************************************************************
  * Descripcion: Cargar Datos DIM_NPS_CALLCENTER
  * Version: 1.0.0
  * Fecha Creacion: 20/01/2020
  * Autor: Byron Vinueza
  * Comentario : Para Ejecutar = CALL CRG_CAT_TIPO_EXONERADO('SQUEMA')
  -------------------------------------------------------------------------
  * Fecha Modificacion:
  * Modificado:
*************************************************************************************************************************/

  DECLARE
	VAR_SQL VARCHAR(4000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN
	

	START TRANSACTION;
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('INTERMEDIA',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_CAT_TIPO_EXONERADO'),VAR_DT_INICIO);
	COMMIT;
	
	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_CAT_TIPO_EXONERADO ;');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

-- GUARDA EN UNA TABLA TEMPORAL LOS REGISTROS ACTUALIZADOS
	
VAR_SQL=CONCAT('CREATE TABLE ',VAR_SCHEMA,'.TMP1_CAT_TIPO_EXONERADO
SELECT   R.ID_TIPO_EXONERADO, 
 IF(NVL(P.TIPO_EXONERADO,R.TIPO_EXONERADO)=R.TIPO_EXONERADO,R.TIPO_EXONERADO,P.TIPO_EXONERADO) TIPO_EXONERADO
  -- ,IF(NVL(P.TIPO_EXONERADO,R.TIPO_EXONERADO)=R.TIPO_EXONERADO,R.TIPO_EXONERADO,CURRENT_TIMESTAMP) FECHA_CARGA
	FROM ',VAR_SCHEMA,'.S3S_CAT_TIPO_EXONERADO R
	LEFT JOIN  ( SELECT DISTINCT TIPO_EXONERADO FROM ',VAR_SCHEMA,'.S3S_SVFCOTI COTI WHERE TIPO_EXONERADO IS NOT NULL ORDER BY 1
	) P ON R.TIPO_EXONERADO=P.TIPO_EXONERADO ;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	-- ELIMINA LOS DATOS DE LA CAT
	VAR_SQL=CONCAT('TRUNCATE TABLE ',VAR_SCHEMA,'.S3S_CAT_TIPO_EXONERADO');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;
 
-- INSERTA LOS DATOS DE LA TMP1 A LA CAT
	VAR_SQL=CONCAT('INSERT INTO ',VAR_SCHEMA,'.S3S_CAT_TIPO_EXONERADO
	(ID_TIPO_EXONERADO,TIPO_EXONERADO)
	SELECT ID_TIPO_EXONERADO,TIPO_EXONERADO
	FROM ' ,VAR_SCHEMA,'.TMP1_CAT_TIPO_EXONERADO ;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP1_CAT_TIPO_EXONERADO');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	-- INSERTA NUEVOS REGISTROS A LA CAT 
	VAR_SQL=CONCAT('INSERT INTO ',VAR_SCHEMA,'.S3S_CAT_TIPO_EXONERADO
	(TIPO_EXONERADO)
	SELECT A.TIPO_EXONERADO
   FROM (SELECT DISTINCT TIPO_EXONERADO FROM ',VAR_SCHEMA,'.S3S_SVFCOTI COTI WHERE TIPO_EXONERADO IS NOT NULL ORDER BY 1) A
	LEFT JOIN  ',VAR_SCHEMA,'.S3S_CAT_TIPO_EXONERADO B ON  A.TIPO_EXONERADO=B.TIPO_EXONERADO
	WHERE B.TIPO_EXONERADO IS NULL ORDER BY 1;
	');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

END;

CALL CRG_CAT_TIPO_EXONERADO('DSA');

SELECT * FROM S3S_CAT_TIPO_EXONERADO;

SHOW CREATE TABLE S3S_CAT_TIPO_EXONERADO;
DROP TABLE CAT_TIPO_EXONERADO;

CREATE TABLE `S3S_CAT_TIPO_EXONERADO` (
  `ID_TIPO_EXONERADO` bigint(11) NOT NULL AUTO_INCREMENT,
  `TIPO_EXONERADO` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  KEY `ID_TIPO_EXONERADO` (`ID_TIPO_EXONERADO`) /*!90619 USING CLUSTERED COLUMNSTORE */
  /*!90618 , SHARD KEY () */ 
) AUTO_INCREMENT=7 /*!90621 AUTOSTATS_ENABLED=TRUE */


